# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/evgeniy/Документы/DED_Projects/SPU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/evgeniy/Документы/DED_Projects/SPU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(CMAKE_COMMAND) -E cmake_progress_start /home/evgeniy/Документы/DED_Projects/SPU/CMakeFiles /home/evgeniy/Документы/DED_Projects/SPU/Onegin//CMakeFiles/progress.marks
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evgeniy/Документы/DED_Projects/SPU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Onegin/CMakeFiles/file_read.dir/rule:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/CMakeFiles/file_read.dir/rule
.PHONY : Onegin/CMakeFiles/file_read.dir/rule

# Convenience name for target.
file_read: Onegin/CMakeFiles/file_read.dir/rule
.PHONY : file_read

# fast build rule for target.
file_read/fast:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/file_read.dir/build.make Onegin/CMakeFiles/file_read.dir/build
.PHONY : file_read/fast

# Convenience name for target.
Onegin/CMakeFiles/test_file_read.dir/rule:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Onegin/CMakeFiles/test_file_read.dir/rule
.PHONY : Onegin/CMakeFiles/test_file_read.dir/rule

# Convenience name for target.
test_file_read: Onegin/CMakeFiles/test_file_read.dir/rule
.PHONY : test_file_read

# fast build rule for target.
test_file_read/fast:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/build
.PHONY : test_file_read/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/main.cpp.s
.PHONY : main.cpp.s

read_from_file.o: read_from_file.cpp.o
.PHONY : read_from_file.o

# target to build an object file
read_from_file.cpp.o:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/file_read.dir/build.make Onegin/CMakeFiles/file_read.dir/read_from_file.cpp.o
.PHONY : read_from_file.cpp.o

read_from_file.i: read_from_file.cpp.i
.PHONY : read_from_file.i

# target to preprocess a source file
read_from_file.cpp.i:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/file_read.dir/build.make Onegin/CMakeFiles/file_read.dir/read_from_file.cpp.i
.PHONY : read_from_file.cpp.i

read_from_file.s: read_from_file.cpp.s
.PHONY : read_from_file.s

# target to generate assembly for a file
read_from_file.cpp.s:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/file_read.dir/build.make Onegin/CMakeFiles/file_read.dir/read_from_file.cpp.s
.PHONY : read_from_file.cpp.s

sort.o: sort.cpp.o
.PHONY : sort.o

# target to build an object file
sort.cpp.o:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/sort.cpp.o
.PHONY : sort.cpp.o

sort.i: sort.cpp.i
.PHONY : sort.i

# target to preprocess a source file
sort.cpp.i:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/sort.cpp.i
.PHONY : sort.cpp.i

sort.s: sort.cpp.s
.PHONY : sort.s

# target to generate assembly for a file
sort.cpp.s:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(MAKE) $(MAKESILENT) -f Onegin/CMakeFiles/test_file_read.dir/build.make Onegin/CMakeFiles/test_file_read.dir/sort.cpp.s
.PHONY : sort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... file_read"
	@echo "... test_file_read"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... read_from_file.o"
	@echo "... read_from_file.i"
	@echo "... read_from_file.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/evgeniy/Документы/DED_Projects/SPU && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

